name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        node: ['20', '22', '24']
    name: Install Dependencies & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run build
        if: ${{ matrix.node == '20' }}
      - name: Archive dist
        if: ${{ matrix.node == '20' }}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  publish-npm:
    name: Publish to NPM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
